spring:
  application:
    name: todo-list-api

  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: platform-database-pool
      auto-commit: true
      connection-timeout: 30000
    url: "jdbc:postgresql://localhost:5500/todoDatabase"
    username: postgres
    password: Senha123
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
