version: '3'

services:
  local-postgres-compose:
    container_name: todo-list-pg
    image: postgres
    environment:
      POSTGRES_PASSWORD: Senha123
      POSTGRES_DB: todoDatabase
    ports:
      - "5500:5432"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge